iris.features.optional = ENTITY_TRANSLUCENT
customTexture.waterNormal = textures/water_normal/mip0.frame0.png
customTexture.waterNormalAtlas = textures/water_normal/atlas.png
screen = WATER_PRESET WATER_NORMAL_MODE WATER_QUALITY SSR_QUALITY SSR_RESOLUTION EXPENSIVE_WATER_DISTANCE CHEAP_WATER_FRESNEL_F0 REFRACTION_MULTIPLIER REFLECTION_MULTIPLIER WATER_NORMAL_SCALE WATER_SPEED_MULTIPLIER REFLECTION_OVERBRIGHT SURFACE_REFRACTION_BLUR UNDERWATER_OVERLAY_MULTIPLIER UNDERWATER_OVERLAY_SCALE
sliders = SSR_RESOLUTION EXPENSIVE_WATER_DISTANCE CHEAP_WATER_FRESNEL_F0 REFRACTION_MULTIPLIER REFLECTION_MULTIPLIER WATER_NORMAL_SCALE WATER_SPEED_MULTIPLIER REFLECTION_OVERBRIGHT SURFACE_REFRACTION_BLUR UNDERWATER_OVERLAY_MULTIPLIER UNDERWATER_OVERLAY_SCALE

#if SSR_QUALITY < 3 && SSR_RESOLUTION < 3 && WATER_QUALITY != 2 && WATER_PRESET != 1
#if SSR_RESOLUTION == 0
size.buffer.colortex2 = 0.25 0.25
#elif SSR_RESOLUTION == 1
size.buffer.colortex2 = 0.5 0.5
#elif SSR_RESOLUTION == 2
size.buffer.colortex2 = 0.75 0.75
#endif
#endif
blend.gbuffers_water.colortex1 = off
blend.gbuffers_water.colortex3 = off

#if SSR_QUALITY >= 3 || SSR_RESOLUTION == 3 || WATER_QUALITY == 2 || WATER_PRESET == 1
program.composite.enabled = false
#endif
